### ISSUE TITLE
VM/Disk naming issue

### ISSUE THREAD

**Issue by andylyall** [greese/dasein-cloud-google#43]
When launching a VM, Dasein first creates a root volume with the same name as the intended VM before launching the VM.
However, GCE has account wide uniqueness requirement for Volume names. Therefore, if the VM has a name matching an existing volume the launch will fail.
Dasein could potentially be modified to find uniqueness when creating the root volumes but something would have to be done to ensure the volume can be deleted safely when the VM is terminated (perhaps set autodelete if possible on root volumes).

**Comment by unwin** [comment]
I modified the code to append the first part of the region to the end of the vm disk name.   Google still errors out with projects/qa-project-2/zones/europe-west1-a/instances/roger-1' already exists.  So it isn't the disk names colliding, but rather the instance names which cannot be the same across regions.

https://www.dropbox.com/s/ighl9bz2bfmf3tn/Screenshot%202015-01-26%2011.50.07.png?dl=0

Recommend this issue be closed.  Alternatively, we would need to append the region to vm names, and disk volume names...

**Comment by andylyall** [comment]
Merged at 2014.11.25-SNAPSHOT
